# syntax: |
#  cli      // when cli and package have same names
#  cli,pkg  // when they differ

# installed with distro package manager
system:
  common: |
    zsh
    fish
    curl
    git
    zip
    unzip
    kitty
  arch: |
    mise
  other: |

# installed with custom package manager (paru, brew)
custom:
  common: |
    fzf
    docker
    docker-compose
    lazydocker
    lazygit
    lazyjournal
    lazyssh
    direnv
    fd
    nvim,neovim
    rg,ripgrep
    wt,worktrunk
  arch: |
    getnf
  other: |

# installed with distro package manager for os with systemd
# Directly in Taskfile
# systemd:

# installed with custom package manager if file does not exist
files:
  common: []
  arch:
    - pkg: zsh-theme-powerlevel10k-git
      file: "$HOME/.p10k.zsh"
    - pkg: zsh-history-substring-search
      file: /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
    - pkg: zsh-autosuggestions
      file: /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
  other:
    - pkg: powerlevel10k
      file: "$HOME/.p10k.zsh"
    - pkg: zsh-history-substring-search
      file: $(brew --prefix)/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
    - pkg: zsh-autosuggestions
      file: $(brew --prefix)/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

sh:
  common: []
  arch: []
  other:
    - pkg: mise
      sh: curl https://mise.run | sh
    - pkg: getnf
      sh: curl -fsSL https://raw.githubusercontent.com/getnf/getnf/main/install.sh | bash
    - pkg: wayscriber
      sh: echo "🛠️ To install wayscriber in current system check `https://wayscriber.com/docs/getting-started/installation.html`"

# installed with custom package manager
devops: |
  kubectl
  k9s
  helm
  stern
  minio

# helm-diff installed via helm, check Taskfile.

# installed with mise
dev:
  common: |
    python
    node
    go
  sh:
    - cli: rustup
      sh: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh && rustup toolchain install stable
