# package installed with distro installer (pacman, dnf, apt)
# TODO: split few having package and cli with different name

# `cli` (with pkg = cli) or `cli,pkg` with coalesce when just cli
test:
  - zsh
  - wt,worktrunk
system:
  - cli: zsh
    pkg: zsh
  - cli: fish
    pkg: fish
  - cli: curl
    pkg: curl
  - cli: git
    pkg: git
  - cli: zip
    pkg: zip
  - cli: unzip
    pkg: unzip
  - cli: kitty
    pkg: kitty
  - cli: mise
    pkg: mise

# installed with AUR/custom installer (paru, brew)
user:
  - cli: fzf
    pkg: fzf
  - cli: docker
    pkg: docker
  - cli: docker-compose
    pkg: docker-compose
  - cli: lazydocker
    pkg: lazydocker
  - cli: lazygit
    pkg: lazygit
  - cli: lazyjournal
    pkg: lazyjournal
  - cli: lazyssh
    pkg: lazyssh
  - cli: direnv
    pkg: direnv
  - cli: fd
    pkg: fd
  - cli: nvim
    pkg: neovim
  - cli: rg
    pkg: ripgrep
  - cli: wt
    pkg: worktrunk

# TODO: 
# [ ] bring back sh installer with dedicated util func 
    
# specific to OS
# ARCH using Paru
user-arch:
  - cli: getnf
    pkg: getnf

files:
  arch:
    - pkg: zsh-theme-powerlevel10k-git
      file: "$HOME/.p10k.zsh"
    - pkg: zsh-history-substring-search
      file: /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
    - pkg: zsh-autosuggestions
      file: /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
  other:
    - pkg: powerlevel10k
      file: "$HOME/.p10k.zsh"
    - pkg: zsh-history-substring-search
      file: $(brew --prefix)/share/zsh-history-substring-search/zsh-history-substring-search.zsh
    - pkg: zsh-autosuggestions
      file: $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# ⚠️ not used
systemd:
  common:
    - cli: keyd
      pkg: keyd
  arch:
    - cli: wayscriber
      pkg: wayscriber

user-devops:
  - kubectl
  - k9s
  - helm
  - helm-diff
  - stern
  - helmwave
  - minio

dev-mise:
  - python
  - node
  - go

dev-sh:
  - cli: rustup
    sh: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh && rustup toolchain install stable
