git:
  # log:
  #   showGraph: always
  paging:
    # colorArg: always
    # useConfig: true
    # colorArg: always
    # pager: diff-so-fancy
    # colorArg: never
    # pager: ydiff -p cat -s --wrap --width={{columnWidth}}
    colorArg: always
    pager: diff-so-fancy
gui:
  sidePanelWidth: 0.25
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      # - "#efdea8"
      - "#e7ce7d"
customCommands:
  - key: b
    command: tig blame -- {{.SelectedFile.Name}}
    context: files
    description: blame file at tree
    output: terminal
  - key: b
    command: tig blame {{.SelectedSubCommit.Sha}} -- {{.SelectedCommitFile.Name}}
    context: commitFiles
    description: blame file at revision
    output: terminal
  - key: B
    command: tig blame -- {{.SelectedCommitFile.Name}}
    context: commitFiles
    description: blame file at tree
    output: terminal
  - key: t
    command: tig show {{.SelectedSubCommit.Sha}}
    context: subCommits
    description: tig commit (`t` again to browse files at revision)
    output: terminal
  - key: t
    command: tig show {{.SelectedLocalBranch.Name}}
    context: localBranches
    description: tig branch (`t` again to browse files at revision)
    output: terminal
  - key: t
    command: tig show {{.SelectedRemoteBranch.RemoteName}}/{{.SelectedRemoteBranch.Name}}
    context: remoteBranches
    description: tig branch (`t` again to browse files at revision)
    output: terminal
  - key: t
    # command: tig {{.SelectedSubCommit.Sha}} -- {{.SelectedCommitFile.Name}}
    command: tig {{.SelectedCommitFile.Name}}
    context: commitFiles
    description: tig file (history of commits affecting file)
    output: terminal
  - key: t
    command: tig -- {{.SelectedFile.Name}}
    context: files
    description: tig file (history of commits affecting file)
    output: terminal
