[keys]
prefix = "ctrl+b"
goto = "prefix+g"
new_tab = "prefix+c"
next_tab = "prefix+n"
previous_tab = "prefix+p"
focus_pane_left = "alt+h"
focus_pane_right = "alt+l"
focus_pane_down = "alt+j"
navigate_workspace_up = "prefix+shift+k"
focus_pane_up = "alt+k"
navigate_workspace_down = "prefix+shift+j"
navigate_pane_down = "ctrl+j"
split_horizontal = "prefix+minus"
